### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by geekyNehal**

### CODE REVIEW

**Comment by SubhrajitPrusty** [comment]
I wont accept this.

At least you could add some badges.
Add Python and Flask badges from http://shields.io/

**Review by SubhrajitPrusty — CHANGES_REQUESTED** [review]
Add Python and Flask badges from http://shields.io/

**Comment by SubhrajitPrusty** [comment]
Why'd you close this? Make the requested changes.

**Comment by geekyNehal** [comment]
ok will do it after midsem!!

**Pull request closed without merging**
